name: API Test Framework

on:
  push:
    branches: [ "mybranch" ]
  pull_request:
    branches: [ "mybranch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute tests
      run: mvn clean test-Dsuite=smoke -X
